modLoader = "javafml"
loaderVersion = "[47,)"
license = "LGPL 3.0"
issueTrackerURL = "https://github.com/ArkTechMC/Neptune/issues"
[[mods]]
modId = "neptune"
version = "${version}"
displayName = "Neptune"
logoFile = "logo.jpg"
authors = "IAFEnvoy"
description = '''
Animation Fan Work Engine
'''
[[dependencies.neptune]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.neptune]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,1.20.2)"
ordering = "NONE"
side = "BOTH"
